<?php

/**
 * @file
 * Generic Parser Live Feeds Module.
 *
 * Provides a custom parser for the Live Feeds module
 *  to parse RSS from the OSU News site.
 */

/**
 * Parser configuration.
 *
 * @returns
 *   A configuration array for this parser
 */
function generic_parser_config() {
  $feed_config = array(
    'feed_type'   => 'generic_parser',
    'feed_title' => 'Generic Parser',
    'feed_url'    => 'http://blogs.oregonstate.edu/feed/rss2',
  );
  return $feed_config;
}

/**
 * Parse the RSS and display the feed.
 *
 * @param string $feed_url
 *   A string containing he URL of the feed.
 * @param int $num_items
 *   An integer containing the number of items to display.
 *
 * @return string|null
 *   A string with the formatted HTML to display
 */
function generic_parser_live_feeds_parser($feed_url, $num_items) {

  // Capture feed.
  $result = drupal_http_request($feed_url);

  if ($result->code !== '200') {
    if (user_is_logged_in()) {
      drupal_set_message('Unable to retrieve specified feed.', 'warning');
    }
    watchdog('live_feeds_generic_parser', 'Unable to retrieve specified feed.', NULL, WATCHDOG_WARNING);
    return;
  }

  // Strip non-print characters from raw feed.
  $file_contents = preg_replace('/[^[:print:]\r\n]/', '', $result->data);

  // Now parse it as XML.
  $xml = simplexml_load_string($file_contents);
  $items = 0;
  $content = '';

  foreach ($xml->channel->item as $story) {
    if (++$items > $num_items) {
      break;
    }

    $date = date('M j, Y', strtotime($story->pubDate));

    $content .= '<div class="news-item">';
    $content .= '<h3 class="title"><a href="' . $story->link . '">' . $story->title . '</a></h3>';
    $content .= '- <div class="date">' . $date . '</div> <br />';
    $content .= '<div class="news-body">' . $story->description . '&nbsp;<a href="' . $story->link . '">Read full story.</a></div></div>';
  }
  return $content;
}
