<?php
/**
 * @file generic_parser.module
 *  Provides a custom parser for the Live Feeds module
 *  to parse RSS from the OSU News site
 */


 /**
  * @returns
  *   A configuration array for this parser
  */
 function generic_parser_config() {
   $feed_config = array(
    'feed_type'   => 'generic_parser',
    'feed_title' => 'Generic Parser',
    'feed_url'    => 'http://blogs.oregonstate.edu/feed/rss2',
  );
  return $feed_config;
}


 /**
 * Parse the RSS and display the feed
 *
 * @param $feed_url
 *  A string containing he URL of the feed
 * @param $num_items
 *  An integer containing the number of items to display
 *
 * @return
 *  A string with the formated HTML to display
 */
function generic_parser_live_feeds_parser($feed_url, $num_items) {

  // Use cURL to get the file
  $proxy = 'proxy.oregonstate.edu:3128';
  $ch = curl_init();
  $timeout = 0;
  curl_setopt ($ch, CURLOPT_URL, $feed_url);
  curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
  curl_setopt($ch, CURLOPT_PROXY, $proxy);
  $file_contents = curl_exec($ch);
  curl_close($ch);

  // Now parse it as XML
  $xml = simplexml_load_string($file_contents);
  $items = 0;
  $content = '';

  foreach ($xml->channel->item as $story) {
    if (++$items > $num_items) break;

    $date = date('M j, Y', strtotime($story->pubDate));

    $content .= '<div class="news-item">';
    $content .= '<h3 class="title"><a href="' . $story->link . '">' . $story->title . '</a></h3>';
    $content .= '- <div class="date">' . $date . '</div> <br />';
    $content .= '<div class="news-body">' . $story->description . '&nbsp;<a href="' . $story->link . '">Read full story.</a></div></div>';
  }
  return $content;
}
