<?php
/**
 * @file osu_announcements.module
 *  Provides a custom parser for the Live Feeds module
 *  to parse RSS from the OSU Announcements module
 */


 /**
  * @returns
  *   A configuration array for this parser
  */
 function osu_announcements_config() {
   $feed_config = array(
    'feed_type'  => 'osu_announcements',
    'feed_title' => 'OSU Announcements',
    'feed_url'   => 'http://oregonstate.edu/cws/announcement/rss.xml',
  );
  return $feed_config;
}


 /**
 * Parse the RSS and display the feed
 *
 * @param $feed_url
 *  A string containing he URL of the feed
 * @param $num_items
 *  An integer containing the number of items to display
 *
 * @return
 *  A string with the formated HTML to display
 */
function osu_announcements_live_feeds_parser($feed_url, $num_items) {

  // Capture feed
  $result = drupal_http_request($feed_url);

  // Strip non-print characters from raw feed
  $file_contents = preg_replace('/[^[:print:]\r\n]/', '', $result->data);

  $xml = simplexml_load_string($file_contents);
  $items = 0;
  $content = '';

  foreach ($xml->channel->item as $item) {
    if (++$items > $num_items) break;

    $date = date('M j, Y', strtotime($item->pubDate));

    // Strip html except for links
    $body = strip_tags($item->description, '<a>');

    $body = live_feeds_truncate_words($body, 25);

    $tidy = new tidy();
    $body = $tidy->repairString($body, array('show-body-only' => 1));

    $content .=  '<div class="news-item">';
    $content .= '<h3 class="title"><a href="' . $item->link . '">' . $item->title . '</a></h3> - ';
    $content .= '<div class="date">'  . $date . '</div>';
    $content .= '<div class="news-body">' . $body . '&hellip; <a href="' . $item->link . '">Read full story.</a></div>';
    $content .= '</div>';
  }
  return $content;
}
