<?php
/**
 * @file ag_jobs.module
 * A live feeds parser for https://rss.myinterfase.com/rss/oregonstate_AG_Jobs.xml
 */


 /**
  * @returns
  *   A configuration array for this parser
  */
 function ag_jobs_config() {
   $feed_config = array(
    'feed_type'   => 'ag_Jobs_parser',
    'feed_title' => 'Ag Jobs Parser',
    'feed_url'    => 'https://rss.myinterfase.com/rss/oregonstate_AG_Jobs.xml',
  );
  return $feed_config;
}


 /**
 * Parse the RSS and display the feed
 *
 * @param $feed_url
 *  A string containing he URL of the feed
 * @param $num_items
 *  An integer containing the number of items to display
 *
 * @return
 *  A string with the formated HTML to display
 */
function ag_jobs_live_feeds_parser($feed_url, $num_items) {

  // Use cURL to get the file
  $proxy = 'proxy.oregonstate.edu:3128';
  $ch = curl_init();
  $timeout = 0;
  curl_setopt ($ch, CURLOPT_URL, $feed_url);
  curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
  curl_setopt($ch, CURLOPT_PROXY, $proxy);
  $file_contents = curl_exec($ch);
  curl_close($ch);

  // Clean up the content:encoded tag
  $file_contents = str_replace("<content:encoded>","<content>",$file_contents);
  $file_contents = str_replace("</content:encoded>","</content>",$file_contents);

  // Now parse it as XML
  $xml = simplexml_load_string($file_contents);
  $items = 0;
  $content = '';

  foreach ($xml->channel->item as $item) {
    if (++$items > $num_items) break;
    $title = $item->title;
    $content .= '<div class="news-item">';
    $content .= '<h3 class="title">' . $item->title . '</h3>';


    $content .= '<div class="news-body">' . $item->content . '</div></div>';
  }
  return $content;
}

/* Data looks like this
<item>
  <title>MILLVILLE VETERINARY CLINIC</title>
  <content:encoded>
    <![CDATA[
      <table cellpadding='1' cellspacing='2'>
        <tr>
          <td>
          <b>Organization Name:</b>
          </td>
          <td>MILLVILLE VETERINARY CLINIC</td>
        </tr>
        <tr>
          <td>
          <b>Website:</b>
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
          <b>Position Title:</b>
          </td>
          <td>ASSOCIATE VETERINARIAN, Northern CA</td>
        </tr>
        <tr>
          <td>
          <b>Job ID:</b>
          </td>
          <td>716</td>
        </tr>
        <tr>
          <td>
          <b>Position Type:</b>
          </td>
          <td>Full-time</td>
        </tr>
        <tr>
          <td>
          <b>Expiration Date:</b>
          </td>
          <td>10/01/2015</td>
        </tr>
        <tr>
          <td colspan='2'>
          <b>
          <a href='https://www.myinterfase.com/oregonstate/job_view.aspx?token=2b+6XG96rn1NI%2fcs6Lvxdg%3d%3d'>Click to View More</a>
          </b>
          </td>
        </tr>
      </table>
    ]]>
  </content:encoded>
</item>

*/



