<?php

/**
 * @file
 * Localist parser.
 *
 * Provides a custom parser for the Live Feeds module
 *  to parse RSS from the OSU Localist Calendar.
 */

/**
 * Defines the Localist event processor.
 *
 * @returns
 *   A configuration array for this parser
 */
function osu_localist_config() {
  $feed_config = array(
    'feed_type' => 'osu_localist',
    'feed_title' => 'OSU Localist',
    'feed_url' => 'https://events.oregonstate.edu/calendar.xml',
  );
  return $feed_config;
}

/**
 * Implements hook_form_alter().
 */
function osu_localist_form_not_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'feed_node_form') {

    drupal_add_js(drupal_get_path('module', 'osu_localist') . '/osu_localist.js');

    $form['live_feeds_form']['date_style'] = array(
      '#type' => 'select',
      '#title' => t('The style of the date in event items'),
      '#description' => t('Select the classic OSU Standard style, or the new Calendar style.'),
      '#options' => array('classic' => 'Classic', 'calendar' => 'Calendar'),
      '#default_value' => variable_get('osu_localist_date_style', 'classic'),
    );
  }
}

/**
 * Implements hook_nodeapi().
 *
 * We have to save the extra fields for this module.
 */
function osu_localist_nodeapi(&$node, $op) {
  if ($node->type == 'feed' && $node->feed_type == 'osu_localist') {
    if ($op == 'insert' || $op == 'update') {
      variable_set('osu_localist_date_style', $node->date_style);
    }
  }
}

/**
 * Parse the RSS and display the feed.
 *
 * @param string $feed_url
 *   A string containing he URL of the feed.
 * @param int $num_items
 *   An integer containing the number of items to display.
 *
 * @return string
 *   A string with the formatted HTML to display
 */
function osu_localist_live_feeds_parser($feed_url, $num_items) {

  // Capture feed.
  $result = drupal_http_request($feed_url);

  // Strip non-print characters from raw feed.
  $file_contents = preg_replace('/[^[:print:]\r\n]/', '', $result->data);
  $file_contents = $result->data;

  $xml = simplexml_load_string($file_contents);
  // Need this to parse the description.
  $html = new DOMDocument('1.0', 'UTF-8');
  // Set error level.
  $internalErrors = libxml_use_internal_errors(TRUE);
  $items = 0;
  $content = '';

  $date_style = variable_get('osu_localist_date_style', 'calendar');

  // Parse the feed_url to determine the calendar link.
  $cal_link = $feed_url;

  foreach ($xml->channel->item as $event) {
    if (++$items > $num_items) {
      break;
    }

    // Get the event data.
    $title = $event->title;
    $link = $event->link;
    $desc = $event->description;

    // Strip date info from title.
    $title = preg_replace("/^[\s\S]*:([\s\S]*)$/i", "$1", $title);

    // Preserve utf8 characters after embedding as html entities.
    $html->loadHTML(mb_convert_encoding((string) $desc, 'HTML-ENTITIES', 'UTF-8'));

    // Remove the date information from the description.
    $date = $event->pubDate;

    // Strip html except for links.
    $desc = strip_tags($desc, '');

    // Parse the date.
    $date = strtotime($date);
    $day = date('d', $date);
    $mon = date('m', $date);
    $month = date('M', $date);
    $year = date('Y', $date);
    $spell_mon = date('F', $date);

    // Get today's date.
    $today_mon = date('m', time());
    $today_day = date('d', time());
    $today_year = date('Y', time());

    // Skip if earlier than today.
    if (
      ($year < $today_year) ||
      ($year == $today_year && $mon < $today_mon) ||
      ($year == $today_year && $mon == $today_mon && $day < $today_day)
    ) {
      $items--;
      continue;
    }

    // Truncate the body and fix all unclosed tags.
    $body = live_feeds_truncate_words(trim($desc), 30);

    // Build output string.
    $content .= '<div class="calendar-item">';
    $content .= '<div class="date ' . $date_style . '">';
    if ($date_style == 'classic') {
      $content .= '<span class="day">';
      $content .= $day;
      $content .= '</span><span class="month"><abbr title="' . $spell_mon . '"> ';
      $content .= $month;
      $content .= '</abbr></span><span class="year">';
      $content .= $year;
      $content .= '</span></div>';
    }
    else {
      $content .= '<div class="month"><abbr title="' . $spell_mon . '">';
      $content .= $month;
      $content .= '</abbr></div><div class="day-year"><div class="day">';
      $content .= $day;
      $content .= '</div><div class="year">';
      $content .= $year;
      $content .= '</div></div></div>';
    }
    $content .= '<div class="description"><p class="title">';
    $content .= '<a href="' . $link . '">';
    $content .= '<strong>' . $title . '</strong></a></p>';
    $content .= $body . '&hellip;</div></div>';
  }
  $content .= '<a href="' . $cal_link . '">View the Entire Calendar</a>';

  // Restore error level.
  libxml_use_internal_errors($internalErrors);
  return $content;
}
