<?php
/**
 * @file cascades_careers.module
 *  Provides a custom parser for the Live Feeds module
 *  to parse RSS from the OSU News site
 */


 /**
  * @returns
  *   A configuration array for this parser
  */
 function cascades_careers_config() {
   $feed_config = array(
    'feed_type'   => 'cascades_careers',
    'feed_title' => 'Career Events',
    'feed_url'    => 'http://blogs.oregonstate.edu/feed/rss2',
  );
  return $feed_config;
}


 /**
 * Parse the RSS and display the feed
 *
 * @param $feed_url
 *  A string containing he URL of the feed
 * @param $num_items
 *  An integer containing the number of items to display
 *
 * @return
 *  A string with the formated HTML to display
 */
function cascades_careers_live_feeds_parser($feed_url, $num_items) {

  // Use cURL to get the file
  $proxy = 'proxy.oregonstate.edu:3128';
  $ch = curl_init();
  $timeout = 0;
  curl_setopt ($ch, CURLOPT_URL, $feed_url);
  curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
  curl_setopt($ch, CURLOPT_PROXY, $proxy);
  $file_contents = curl_exec($ch);
  curl_close($ch);

  // Now parse it as XML
  $xml = simplexml_load_string($file_contents);
  $items = 0;
  $content = '';

  foreach ($xml->channel->item as $story) {
    if (++$items > $num_items) break;

    $desc   = $story->children('content', true)->encoded;

    /* Finding the Date: */
    preg_match('/[0-9]*\/[0-9]*\/[0-9]*/', $desc, $dates);
    $date   = $dates[0];

    /* Finding the Link: */
    preg_match("/<a href='(.*)'>/", $desc, $links);
    $link   = $links[1];

    /*Finding the Location: */
    preg_match("/Location:<\/b><\/td><td>((\w*\s*)*)/", $desc, $locations);
    $location = $locations[1];

    $content .= '<div class="news-item">';
    $content .= '<h3 class="title"><a href="' . $link . '">' . $story->title . '</a></h3>';
    $content .= '- <div class="date">' . $date . '</div> <br />';
    $content .= '<div class="news-body">Location: ' . $location . '<br><a href="' . $link . '">Click to view more.</a></div></div>';
  }
  return $content;
}
