<?php
/**
 * @file osu_events.php
 *  Provides a custom parser for the Feeds Display module
 *  to parse RSS from the OSU Events Calendar
 */


 /**
  * @returns
  *   A configuration array for this parser
  */
 function osu_events_config() {
   $feed_config = array(
    'feed_type'   => 'osu_events',
    'feed_title'  => 'OSU Events',
    'feed_url'    => 'http://calendar.oregonstate.edu/osu/rss20.xml',
  );
  return $feed_config;
}


 /**
 * Parse the RSS and display the feed
 *
 * @param $feed_url
 *  A string containing he URL of the feed
 * @param $num_items
 *  An integer containing the number of items to display
 *
 * @return
 *  A string with the formated HTML to display
 */
function osu_events_feeds_display_parser($feed_url, $num_items) {

  $xml = simplexml_load_file("$feed_url");
  $html = new DOMDocument; // Need this to parse the description

  // Parse the feed_url to determine the calendar link
 preg_match('/\/(\w+-*\w*-*\w*)\/rss20.xml/', $feed_url, $match);
 $cal_link = 'http://calendar.oregonstate.edu/' . $match[1];

  foreach ($xml->channel->item as $event) {
    if ($items++ > $num_items) break;

    // Get the event data
    $title = $event->title;
    $link  = $event->link;
    $desc  = $event->description;

    // Remove the date div from the description
    $html->loadHTMl( (string) $desc);
    $date = $html->getElementsByTagName('div')->item(0);
    $div = $date->parentNode;
    $div->removeChild($date);

    $desc = utf8_decode($html->saveXML($div));

    // Start and end dates use the osu namespace
    $nodes = $event->children('edu.oregonstate.calendar', true);
    $start = $nodes->dtstart;
    $end   = $nodes->dtend;

    // Parse the date
    $date  = strtotime($start);
    $day   = date('d', $date);
    $mon   = date('m', $date);
    $month = date('M', $date);
    $year  = date('Y', $date);

    // Get today's date
    $today_mon  = date('m', time());
    $today_day  = date('d', time());
    $today_year = date('Y', time());

    // Skip if earlier than today
    if (
      ($year < $today_year) ||
      ($year == $today_year && $mon < $today_mon) ||
      ($year == $today_year && $mon == $today_mon && $day < $today_day)
    ) {
      $items--;
      continue;
    }

    // Trucate the body and fix all unclosed tags
    $body = feeds_display_truncate_words(trim($desc), 30);
    $tidy = new tidy();
    $body = $tidy->repairString($body, array('show-body-only' => 1));

    // Build output string
    $content .= '<div class="calendar-item">';
    $content .= '<div class="date"><span class="day">';
    $content .= $day;
    $content .= '</span><span class="month">';
    $content .= $month;
    $content .= '</span><span class="year">';
    $content .= $year;
    $content .= '</span></div>';
    $content .= '<div class="description"><p class="title">';
    $content .= '<a href="' . $link . '">';
    $content .= '<strong>' . $title . '</strong></a></p>';
    $content .= $body . '&hellip;</div></div>';
  }
  $content .= '<a href="' . $cal_link . '">View the Entire Calendar</a>';
  return $content;
}



