<?php

/**
 * @file
 * OSU News Live Feeds Plugin.
 *
 * Provides a custom parser for the Live Feeds  module
 *  to parse RSS from the OSU News site.
 */

/**
 * Parser configuration.
 *
 * @returns
 *   A configuration array for this parser
 */
function osu_news_config() {
  $feed_config = array(
    'feed_type' => 'osu_news',
    'feed_title' => 'OSU News',
    'feed_url' => 'https://today.oregonstate.edu/releases/feed/',
  );
  return $feed_config;
}

/**
 * Parse the RSS and display the feed.
 *
 * @param string $feed_url
 *   A string containing the URL of the feed.
 * @param int $num_items
 *   An integer containing the number of items to display.
 *
 * @return string|null
 *   A string with the formated HTML to display
 */
function osu_news_live_feeds_parser($feed_url, $num_items) {

  // Capture feed.
  $result = drupal_http_request($feed_url);

  if ($result->code !== '200') {
    drupal_set_message('Unable to retrieve specified feed.', 'warning');
    watchdog('live_feeds_osu_news', 'Unable to retrieve specified feed.', NULL, WATCHDOG_WARNING);
    return;
  }

  // Strip non-print characters from raw feed.
  $file_contents = preg_replace('/[^[:print:]\r\n]/', '', $result->data);

  $items = 0;
  $content = '';

  $xml = simplexml_load_string($file_contents);
  // Need this to parse the description.
  $html = new DOMDocument('1.0', 'UTF-8');

  // Set error level.
  $internalErrors = libxml_use_internal_errors(TRUE);

  foreach ($xml->channel->item as $story) {
    if (++$items > $num_items) {
      break;
    }

    // Don't reuse content from previous iteration.
    unset($teaser);

    // Parse the description into HTML divs and look for specific classes.
    $html->loadHTML($story->description);

    $teaser = $html->getElementsByTagName('div')->item(0)->nodeValue;
    $body = $html->getElementsByTagName('div')->item(1)->nodeValue;
    $content .= '<div class="news-item">';
    $content .= '<img typeof="foaf:Image" src="' . (string) $story->enclosure['url'] . '" width="75" height="75" alt="OSU News Release" />';
    $content .= '<h3 class="title">' . substr($story->link, 0, -8) . $story->title . '</a></h3> - ';
    $content .= '<div class="date">' . date('M j, Y', strtotime($story->pubDate)) . '</div>';

    // Display teaser if there is one, else truncate body.
    if (isset($teaser)) {
      $content .= '<div class="news-body">' . $teaser . '&hellip; ' . substr($story->link, 0, -8) . 'Read full story.</a></div>';
    } else {
      $content .= '<div class="news-body">' . live_feeds_truncate_words(trim($body), 20) . '&hellip; ' . substr($story->link, 0, -8) . 'Read full story.</a></div>';
    }
    $content .= '</div>';
  }
  // Restore error level.
  libxml_use_internal_errors($internalErrors);
  return $content;
}
