<?php

/**
 * @file
 * OSU Wordpress Live Feeds Plugin.
 *
 * Provides a custom parser for the Live Feeds module
 *  to parse RSS from the OSU News site.
 */

/**
 * Parser configuration.
 *
 * @returns
 *   A configuration array for this parser
 */
function osu_wordpress_config() {
  $feed_config = [
    'feed_type' => 'osu_wordpress',
    'feed_title' => 'OSU WordPress',
    'feed_url' => 'http://blogs.oregonstate.edu/feed/rss2',
  ];
  return $feed_config;
}

/**
 * Parse the RSS and display the feed.
 *
 * @param string $feed_url
 *   A string containing he URL of the feed.
 * @param int $num_items
 *   An integer containing the number of items to display.
 *
 * @return string|null
 *   A string with the formated HTML to display
 */
function osu_wordpress_live_feeds_parser($feed_url, $num_items) {

  // Capture feed.
  $result = drupal_http_request($feed_url);

  if ($result->code !== '200') {
    if (user_is_logged_in()) {
      drupal_set_message('Unable to retrieve specified feed.', 'warning');
    }
    watchdog('live_feeds_osu_wordpress', 'Unable to retrieve specified feed.', NULL, WATCHDOG_WARNING);
    return;
  }

  $file_contents = $result->data;
  $xml = simplexml_load_string($file_contents, "SimpleXMLElement", LIBXML_NOCDATA);
  $items = 0;
  $content = '';

  foreach ($xml->channel->item as $story) {
    if (++$items > $num_items) {
      break;
    }

    $date = date('M j, Y', strtotime($story->pubDate));

    $content .= '<div class="news-item">';
    $content .= '<h3 class="title">' . l($story->title, $story->link) . '</h3>';
    $content .= '- <div class="date">' . $date . '</div> <br />';
    $content .= '<div class="news-body">' . $story->description . '</div></div>';
  }
  return $content;
}
