<?php
/**
 * @file osu_wordpress.module
 *  Provides a custom parser for the Live Feeds module
 *  to parse RSS from the OSU News site
 */


 /**
  * @returns
  *   A configuration array for this parser
  */
 function osu_wordpress_config() {
   $feed_config = array(
    'feed_type'   => 'osu_wordpress',
    'feed_title' => 'OSU WordPress',
    'feed_url'    => 'http://blogs.oregonstate.edu/feed/rss2',
  );
  return $feed_config;
}


 /**
 * Parse the RSS and display the feed
 *
 * @param $feed_url
 *  A string containing he URL of the feed
 * @param $num_items
 *  An integer containing the number of items to display
 *
 * @return
 *  A string with the formated HTML to display
 */
function osu_wordpress_live_feeds_parser($feed_url, $num_items) {

  $feed_url .= (substr($feed_url, -1) == '/' ? '' : '/');

  // Capture feed
  $result = drupal_http_request($feed_url);

  // Strip non-print characters from raw feed
  $file_contents = preg_replace('/[^[:print:]\r\n]/', '', $result->data);
  //$file_contents = $result->data;
    
  $xml = simplexml_load_string($file_contents);
  $items = 0;
  $content = '';

  foreach ($xml->channel->item as $story) {
    if (++$items > $num_items) break;

    $date = date('M j, Y', strtotime($story->pubDate));

    $content .= '<div class="news-item">';
    $content .= '<h3 class="title"><a href="' . $story->link . '">' . $story->title . '</a></h3>';
    $content .= '- <div class="date">' . $date . '</div> <br />';
    $content .= '<div class="news-body">' . $story->description . '</div></div>';
  }
  return $content;
}
