<?php
/**
 * @file osu_event_cal.php
 *  Provides a custom parser for the Feeds Display module
 *  to parse RSS from the OSU Events Calendar
 */


 /**
  * @returns
  *   A configuration array for this parser
  */
 function osu_event_cal_config() {
   $feed_config = array(
    'feed_type'   => 'osu_event_cal',
    'feed_title'  => 'OSU Events Calendar',
    'feed_url'    => 'http://dev.calendar.oregonstate.edu/MasterCalendar/RSSFeeds.aspx?Name=cws_training_rss',
  );
  return $feed_config;
}


 /**
 * Parse the RSS and display the feed
 *
 * @param $feed_url
 *  A string containing he URL of the feed
 * @param $num_items
 *  An integer containing the number of items to display
 *
 * @return
 *  A string with the formated HTML to display
 */
function osu_event_cal_feeds_display_parser($feed_url, $num_items) {
  $xml = simplexml_load_file("$feed_url");

  foreach ($xml->channel->item as $event) {
    if (++$items > $num_items) break;

    // Get the event data
    $title = $event->title;
    $link  = $event->link;
    $desc  = $event->description;
    $date  = $event->pubDate; //>Tue, 24 Jan 2012 22:00:00 GMT</pubDate>

     // Parse the date
    $date  = strtotime($date);
    $day   = date('d', $date);
    $month = date('M', $date);
    $year  = date('Y', $date);

    // Trucate the body and fix all unclosed tags
    $body = feeds_display_truncate_words(trim($desc), 30);
    $tidy = new tidy();
    $body = $tidy->repairString($body, array('show-body-only' => 1));

    // Build output string
    $content .= '<div class="calendar-item">';  

    $content .= '<div class="date calendar" >';
    $content .= '<div class="month">';
    $content .= $month;
    $content .= '</div><div class="day-year"><div class="day">';
    $content .= $day;
    $content .= '</div><div class="year">';
    $content .= $year;
    $content .= '</div></div></div>';
 
    $content .= '<div class="description"><p class="title">';
    $content .= '<a href="' . $link . '">';
    $content .= '<strong>' . $title . '</strong></a></p>';
    $content .= $body . '&hellip;</div></div>';
  }

  return $content;
}


