<?php
/**
 * @file beaver_jobs.module
 * A live feeds parser for https://rss.myinterfase.com/rss/oregonstate_beaver_jobs.xml
 */


 /**
  * @returns
  *   A configuration array for this parser
  */
 function beaver_jobs_config() {
   $feed_config = array(
    'feed_type'   => 'beaver_jobs',
    'feed_title'  => 'Beaver Jobs',
    'feed_url'    => 'https://rss.myinterfase.com/rss/oregonstate_Beaver_Careers_Jobs.xml',
  );
  return $feed_config;
}


 /**
 * Parse the RSS and display the feed
 *
 * @param $feed_url
 *  A string containing he URL of the feed
 * @param $num_items
 *  An integer containing the number of items to display
 *
 * @return
 *  A string with the formated HTML to display
 */
function beaver_jobs_live_feeds_parser($feed_url, $num_items) {

  // Capture feed
  $result = drupal_http_request($feed_url);

  // Strip non-print characters from raw feed
  $file_contents = preg_replace('/[^[:print:]\r\n]/', '', $result->data);

  // Convert up the content:encoded tag into something we can parse
  $file_contents = str_replace("<content:encoded>","<content>",$file_contents);
  $file_contents = str_replace("</content:encoded>","</content>",$file_contents);

  // Now parse it as XML
  $xml = simplexml_load_string($file_contents);
  $items = 0;
  $content = '';

  foreach ($xml->channel->item as $item) {
    if (++$items > $num_items) break;
    $title = $item->title;
    $content .= '<div class="news-item">';
    $content .= '<h3 class="title">' . $item->title . '</h3>';
    $content .= '<div class="news-body">' . $item->content . '</div></div>';
  }
  return $content;
}



